### ISSUE TITLE
Trying to use pip to install framework

### ISSUE THREAD

**Issue by kswain1** [bnmnetp/pythonds#3]
Is there anyway you can include a setup.py for use to pip install your project into their system? Thank you for your time, and I am a student of the class.

**Comment by bnmnetp** [comment]
I will add this to my todo list.   But it will not happen for a couple of weeks.

**Comment by bnmnetp** [comment]
OK, 

```
pip install pythonds
```

will work now.

**Comment by kswain1** [comment]
thanks man!
